-- Manual
--

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO users (id, username, email, created_at)
VALUES
    (1, 'vasya', 'vasya@app.test', '2022-10-10 11:30:30'),
    (2, 'petya', 'petya@app.test', '2023-12-11 12:32:16');

SELECT * FROM users;

-- Sequence
--

DROP TABLE users;
DROP SEQUENCE IF EXISTS users_id_seq;

CREATE SEQUENCE users_id_seq;

CREATE TABLE users (
    id INTEGER PRIMARY KEY DEFAULT nextval('users_id_seq'),
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER SEQUENCE users_id_seq OWNED BY users.id;

INSERT INTO users (id, username, email, created_at)
VALUES
    (default, 'vasya', 'vasya@app.test', '2022-10-10 11:30:30'),
    (default, 'petya', 'petya@app.test', '2023-12-11 12:32:16');

SELECT * FROM users;

TRUNCATE users;

INSERT INTO users (username, email, created_at)
VALUES
    ('vasya', 'vasya@app.test', '2022-10-10 11:30:30'),
    ('petya', 'petya@app.test', '2023-12-11 12:32:16');

SELECT * FROM users;

-- Sequence Conflict
--

DROP TABLE users;
DROP SEQUENCE IF EXISTS users_id_seq;

CREATE SEQUENCE users_id_seq;

CREATE TABLE users (
    id INTEGER PRIMARY KEY DEFAULT nextval('users_id_seq'),
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO users (id, username, email, created_at)
VALUES
    (1, 'vasya', 'vasya@app.test', '2022-10-10 11:30:30'),
    (2, 'petya', 'petya@app.test', '2023-12-11 12:32:16'),
    (3, 'oleg', 'oleg@app.test', '2023-12-11 12:32:16');

-- INSERT INTO users (username, email, created_at)
-- VALUES
--     ('vlad', 'vlad@app.test', '2022-10-10 11:30:30'),
--     ('ilya', 'ilya@app.test', '2023-12-11 12:32:16');

-- SELECT currval('users_id_seq');

SELECT setval('users_id_seq', 3);
SELECT setval('users_id_seq', (SELECT max(id) FROM users));
SELECT setval('users_id_seq', 4, false);

INSERT INTO users (username, email, created_at)
VALUES
    ('vlad', 'vlad@app.test', '2022-10-10 11:30:30'),
    ('ilya', 'ilya@app.test', '2023-12-11 12:32:16');

SELECT * FROM users;

-- Serial
--

DROP TABLE users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO users (username, email, created_at)
VALUES
    ('vasya', 'vasya@app.test', '2022-10-10 11:30:30'),
    ('petya', 'petya@app.test', '2023-12-11 12:32:16');

SELECT * FROM users;

-- Generated
--

DROP TABLE users;

CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO users (id, username, email, created_at)
VALUES
    (1, 'vasya', 'vasya@app.test', '2022-10-10 11:30:30'),
    (2, 'petya', 'petya@app.test', '2023-12-11 12:32:16'),
    (3, 'oleg', 'oleg@app.test', '2023-12-11 12:32:16');

SELECT setval('users_id_seq', (SELECT max(id) FROM users));

INSERT INTO users (username, email, created_at)
VALUES
    ('vlad', 'vlad@app.test', '2022-10-10 11:30:30'),
    ('ilya', 'ilya@app.test', '2023-12-11 12:32:16');

SELECT * FROM users;

-- Default
--

DROP TABLE users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, username, email, created_at)
VALUES
    (default, 'vasya', 'vasya@app.test', default),
    (default, 'petya', 'petya@app.test', default);

SELECT * FROM users;

-- Add column
--

DROP TABLE users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL
);

INSERT INTO users (id, username, email)
VALUES
    (default, 'vasya', 'vasya@app.test'),
    (default, 'petya', 'petya@app.test');

SELECT * FROM users;

ALTER TABLE users ADD COLUMN created_at TIMESTAMP;

SELECT * FROM users;

ALTER TABLE users DROP COLUMN created_at;

-- ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL;

ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

SELECT * FROM users;

ALTER TABLE users DROP COLUMN created_at;
-- ALTER TABLE users DROP COLUMN created_at CASCADE;

SELECT * FROM users;

ALTER TABLE users ADD COLUMN created_at TIMESTAMP;
UPDATE users SET created_at = '2025-01-01 00:00:00' WHERE created_at IS NULL;
ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

SELECT * FROM users;

--