services:
    db:
        image: postgres:17.4-alpine3.21
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --user postgres" ]
            interval: 1s
            timeout: 1s
            retries: 10

    client:
        build:
            context: client
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - ./example:/app:ro
        depends_on:
            db:
                condition: service_healthy

    php:
        build:
            context: php
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - ./example:/app:ro
        depends_on:
            db:
                condition: service_healthy

volumes:
    db:
